### ISSUE TITLE
Anmeldeoption für den Benutzer

### ISSUE THREAD

**Issue by CrazyDenzi** [colichri/webProgramming-BackEnd#25]

**Comment by CrazyDenzi** [comment]
Ist das Issue für Frontend oder Backend gedacht? @colichri @Grabkaazz @Milan-Je

**Comment by colichri** [comment]
Hmm weiß ich gerade selbst nicht, aber im Zweifel ist das Back End. Des Repo hier wollen wir ja auch auf Back End umstellen und ein neues Repo für Front End aufmachen
